// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Migrator")]
[assembly: AssemblyProductAttribute("MongoMigrator")]
[assembly: AssemblyDescriptionAttribute("A repeatable, deterministic mongo script runner.")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0";
    }
}
