// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("RunMongoRun")]
[assembly: AssemblyProductAttribute("RunMongoRun")]
[assembly: AssemblyDescriptionAttribute("A repeatable, deterministic mongo script runner.")]
[assembly: AssemblyVersionAttribute("0.2.0")]
[assembly: AssemblyFileVersionAttribute("0.2.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.2.0";
    }
}
